# server.port: 8082

# spring:
#   application:
#     name: gateway-service
#   cloud:
#     gateway:
#       discovery:
#         locator:
#           enabled: true
#           lowerCaseServiceId: true

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
#     enabled: true
#     registerWithEureka: false
#     fetchRegistry: true
#     initialInstanceInfoReplicationIntervalSeconds: 5
#     registryFetchIntervalSeconds: 5
#   instance:
#     leaseRenewalIntervalInSeconds: 5
#     leaseExpirationDurationInSeconds: 5
#     hostname: localhost
#     preferIpAddress: true

# logging:
#   root: ALL

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
