server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

hystrix:
  command:
    fallbackCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: clientFrontendModule
          uri: lb://client-frontend
          predicates:
            - Path=/**
          filters:
            - name: Hystrix
              args:
                name: fallbackCommand
                fallbackUri: forward:/fallback/message
